# 🧠 Feature Construction

### 👉 The process of creating new meaningful features (columns) from raw data so that the Machine Learning model learns better.

## 🔍 Example (Simple Understanding)
#### Raw data:
##### Age = 25
##### Height = 170 cm
##### Weight = 70 kg

#### Constructed feature:
##### BMI = Weight / (Height/100)^2

## 🔰 Import Library

In [1]:
import pandas as pd

## 🔰 Load CSV file

In [2]:
df = pd.read_csv("mobile_project.csv")

In [3]:
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [4]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

## 🔰 Required the columns

In [6]:
df1 = pd.read_csv("mobile_project.csv")[["sc_h", "sc_w"]]

In [7]:
df1

      sc_h  sc_w
0        9     7
1       17     3
2       11     2
3       16     8
4        8     2
...    ...   ...
1995    13     4
1996    11    10
1997     9     1
1998    18    10
1999    19     4

[2000 rows x 2 columns]

## 🔰 Drop the null value

In [8]:
df1.dropna()

      sc_h  sc_w
0        9     7
1       17     3
2       11     2
3       16     8
4        8     2
...    ...   ...
1995    13     4
1996    11    10
1997     9     1
1998    18    10
1999    19     4

[2000 rows x 2 columns]

## 🔰 Feature Construction

In [9]:
df1["sc_area"] = df1["sc_h"] * df1["sc_w"]

In [10]:
df1

      sc_h  sc_w  sc_area
0        9     7       63
1       17     3       51
2       11     2       22
3       16     8      128
4        8     2       16
...    ...   ...      ...
1995    13     4       52
1996    11    10      110
1997     9     1        9
1998    18    10      180
1999    19     4       76

[2000 rows x 3 columns]

In [12]:
df1.min()

sc_h       5
sc_w       0
sc_area    0
dtype: int64

In [13]:
df1.max()

sc_h        19
sc_w        18
sc_area    342
dtype: int64

In [14]:
def mymobile(screen):
    if screen >= 228:
        return "Heavy"
    elif screen >= 114 :
        return "Mediam"
    else:
        return "Light"

In [15]:
df1["sc_type"] = df1["sc_area"].apply(mymobile)

In [16]:
df1

      sc_h  sc_w  sc_area sc_type
0        9     7       63   Light
1       17     3       51   Light
2       11     2       22   Light
3       16     8      128  Mediam
4        8     2       16   Light
...    ...   ...      ...     ...
1995    13     4       52   Light
1996    11    10      110   Light
1997     9     1        9   Light
1998    18    10      180  Mediam
1999    19     4       76   Light

[2000 rows x 4 columns]