# 🔤 One Hot Encoding with Real CSV

## 🔰 Import Library

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

## 🔰 Load CSV File

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [4]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

## 🔰 Convert To OneHotEncoding

## 🔰 Method : 1 (Simple Method)

In [5]:
embarked_encoder = pd.get_dummies(df["Embarked"], prefix="Embarked")

In [6]:
embarked_encoder

     Embarked_C  Embarked_Q  Embarked_S
0         False       False        True
1          True       False       False
2         False       False        True
3         False       False        True
4         False       False        True
..          ...         ...         ...
886       False       False        True
887       False       False        True
888       False       False        True
889        True       False       False
890       False        True       False

[891 rows x 3 columns]

In [7]:
df = pd.concat([df, embarked_encoder], axis=1)

In [8]:
df

     PassengerId  Survived  Pclass  ... Embarked_C Embarked_Q  Embarked_S
0              1         0       3  ...      False      False        True
1              2         1       1  ...       True      False       False
2              3         1       3  ...      False      False        True
3              4         1       1  ...      False      False        True
4              5         0       3  ...      False      False        True
..           ...       ...     ...  ...        ...        ...         ...
886          887         0       2  ...      False      False        True
887          888         1       1  ...      False      False        True
888          889         0       3  ...      False      False        True
889          890         1       1  ...       True      False       False
890          891         0       3  ...      False       True       False

[891 rows x 15 columns]

## 🔰 Method : 2 (Complex Method)

In [9]:
encoder = OneHotEncoder()

In [10]:
encoders = OneHotEncoder(sparse_output=False)

In [11]:
onehotcoder = encoders.fit_transform([["Sex", "Embarked"]])

In [12]:
df1 = pd.DataFrame(onehotcoder, columns=encoders.get_feature_names_out(["Sex", "Embarked"]))

In [13]:
df1

   Sex_Sex  Embarked_Embarked
0      1.0                1.0

In [16]:
df = pd.concat([df.reset_index(drop=True).drop(columns=["Sex", "Embarked"]), df1.reset_index(drop=True)], axis=1)

In [17]:
df

     PassengerId  Survived  Pclass  ... Embarked_S  Sex_Sex  Embarked_Embarked
0              1         0       3  ...       True      1.0                1.0
1              2         1       1  ...      False      NaN                NaN
2              3         1       3  ...       True      NaN                NaN
3              4         1       1  ...       True      NaN                NaN
4              5         0       3  ...       True      NaN                NaN
..           ...       ...     ...  ...        ...      ...                ...
886          887         0       2  ...       True      NaN                NaN
887          888         1       1  ...       True      NaN                NaN
888          889         0       3  ...       True      NaN                NaN
889          890         1       1  ...      False      NaN                NaN
890          891         0       3  ...      False      NaN                NaN

[891 rows x 15 columns]