# 🔤 Ordinal Encoding with Real CSV

## 🔰 Import Library

In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

## 🔰 Load CSV File

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [6]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

## 🔰 Convert To OrdinalEncoding

In [14]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [16]:
df["Embarked"].fillna("S", inplace=True)

In [17]:
coder = OrdinalEncoder(categories=[["S", "C", "Q"]])

In [18]:
df["Embarked_encoder"] = coder.fit_transform(df[["Embarked"]])

In [19]:
df["Embarked_encoder"]

0      0.0
1      1.0
2      0.0
3      0.0
4      0.0
      ...
886    0.0
887    0.0
888    0.0
889    1.0
890    2.0
Name: Embarked_encoder, Length: 891, dtype: float64

In [20]:
df

     PassengerId  Survived  Pclass  ... Cabin Embarked  Embarked_encoder
0              1         0       3  ...   NaN        S               0.0
1              2         1       1  ...   C85        C               1.0
2              3         1       3  ...   NaN        S               0.0
3              4         1       1  ...  C123        S               0.0
4              5         0       3  ...   NaN        S               0.0
..           ...       ...     ...  ...   ...      ...               ...
886          887         0       2  ...   NaN        S               0.0
887          888         1       1  ...   B42        S               0.0
888          889         0       3  ...   NaN        S               0.0
889          890         1       1  ...  C148        C               1.0
890          891         0       3  ...   NaN        Q               2.0

[891 rows x 13 columns]