# 🔴 Ordinal Encoding

### 👉 Education, Rating, Size (order matters)

### 👉 Ordinal Encoding converts text to numbers while keeping the correct order.

### 👉 Used when categories have a meaningful order.

## ✅ Import Library

In [1]:
import pandas as pd

## ✅ DataFrame

In [2]:
data = { "Performance": ["High", "Medium", "Low", "High", "Medium"] }

In [3]:
data

{'Performance': ['High', 'Medium', 'Low', 'High', 'Medium']}

## ✅ Method : 1

In [4]:
df = pd.DataFrame(data)

In [5]:
df

  Performance
0        High
1      Medium
2         Low
3        High
4      Medium

In [6]:
order = { "Low":0 ,"Medium":1 ,"High":2}

In [7]:
order

{'Low': 0, 'Medium': 1, 'High': 2}

In [8]:
df["Performance_Encoder"] = df["Performance"].map(order)

In [9]:
df["Performance_Encoder"]

0    2
1    1
2    0
3    2
4    1
Name: Performance_Encoder, dtype: int64

In [10]:
df

  Performance  Performance_Encoder
0        High                    2
1      Medium                    1
2         Low                    0
3        High                    2
4      Medium                    1

## ✅ Method : 2

## ✅ Import Library

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
encoder = OrdinalEncoder()

In [13]:
encoders = OrdinalEncoder(categories=[["Low", "Medium", "High"]])

In [15]:
df["Performance_Encoder_2"] = encoders.fit_transform(df[["Performance"]])

In [16]:
df["Performance_Encoder_2"]

0    2.0
1    1.0
2    0.0
3    2.0
4    1.0
Name: Performance_Encoder_2, dtype: float64

In [17]:
df

  Performance  Performance_Encoder  Performance_Encoder_2
0        High                    2                    2.0
1      Medium                    1                    1.0
2         Low                    0                    0.0
3        High                    2                    2.0
4      Medium                    1                    1.0