# 🧱 Feature Scaling with Real CSV (Normalization (Min–Max Scaling))

## 🔰 Import Libary

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

## 🔰 Load CSV File

In [2]:
df = pd.read_csv("mobile_project.csv")

In [3]:
df

      battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0               842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1              1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2               563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3               615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4              1821     1          1.2         0  13       1  ...     2         15        1             1     0            1
...             ...   ...          ...       ...  ..     ...  ...   ...        ...      ...           ...   ...          ...
1995            794     1          0.5         1   0       1  ...     4         19        1             1     0            0
1996           1965     1          2.6         1   0       0  ...    10         16        1             1     1            2
1997           1911     0          0.9         1   1       1  ...     1          5        1             1     0            3
1998           1512     0          0.9         0   4       1  ...    10         19        1             1     1            0
1999            510     1          2.0         1   5       1  ...     4          2        1             1     1            3

[2000 rows x 21 columns]

In [4]:
df.head()

   battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0            842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1           1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2            563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3            615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4           1821     1          1.2         0  13       1  ...     2         15        1             1     0            1

[5 rows x 21 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

## 🔰 Use Of Scaler Variable

In [6]:
battery = df[["battery_power"]]

In [7]:
battery

      battery_power
0               842
1              1021
2               563
3               615
4              1821
...             ...
1995            794
1996           1965
1997           1911
1998           1512
1999            510

[2000 rows x 1 columns]

In [8]:
battery.min()

battery_power    501
dtype: int64

In [9]:
battery.max()

battery_power    1998
dtype: int64

## 🔰 Object and Transform

In [10]:
scaler = MinMaxScaler()

In [11]:
battery_scaler = scaler.fit_transform(battery)

## 🔰 Convert To Array

In [12]:
battery_scaler = np.array(battery_scaler)

In [13]:
battery_scaler

array([[0.22778891],
       [0.34736139],
       [0.04141617],
       ...,
       [0.94188377],
       [0.6753507 ],
       [0.00601202]], shape=(2000, 1))

## 🔰 Check The Value

In [14]:
battery_scaler.min()

np.float64(0.0)

In [15]:
battery_scaler.max()

np.float64(1.0)