# 🤖 KNN (K-Nearest Neighbors) Regressor

## 🔰 Import Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score

## 🔰 Load CSV

In [2]:
df = pd.read_csv("knn_regression_house_price_dataset.csv")

In [3]:
df

     area_sqft  bedrooms  house_age  distance_city_km      price
0         1360         4         29              3.00  186418.85
1         1794         4         18              3.20  233288.42
2         1630         2         16             15.46  185510.14
3         1595         3         23             14.29  173915.36
4         2138         1         18              6.11  245415.03
..         ...       ...        ...               ...        ...
195       1995         4         13              8.72  263668.35
196       1636         5         19              3.21  216685.29
197       2353         2         18             12.55  286878.85
198       2020         4         25             17.51  252076.28
199       2989         2         14             13.28  387280.39

[200 rows x 5 columns]

In [4]:
df.head()

   area_sqft  bedrooms  house_age  distance_city_km      price
0       1360         4         29              3.00  186418.85
1       1794         4         18              3.20  233288.42
2       1630         2         16             15.46  185510.14
3       1595         3         23             14.29  173915.36
4       2138         1         18              6.11  245415.03

## 🔰 Features & Target

In [5]:
x = df.drop("price", axis=1)

In [6]:
y = df["price"]

## 🔰 Train-Test Split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaled = StandardScaler()
x_train = scaled.fit_transform(x_train)
x_test = scaled.transform(x_test)

In [10]:
df.head()

   area_sqft  bedrooms  house_age  distance_city_km      price
0       1360         4         29              3.00  186418.85
1       1794         4         18              3.20  233288.42
2       1630         2         16             15.46  185510.14
3       1595         3         23             14.29  173915.36
4       2138         1         18              6.11  245415.03

## 🔰 Train Decision Tree Model

In [11]:
model = KNeighborsRegressor(n_neighbors = 5)

In [12]:
model.fit(x_train, y_train)

KNeighborsRegressor()

## 🔰 Prediction

In [13]:
y_pred = model.predict(x_test)

In [14]:
y_pred

array([307935.756, 345922.002, 323922.298, 209176.484, 218509.994,
       116911.42 , 200164.778, 291761.002, 307064.846, 274533.934,
       224221.992, 116964.544, 371143.984, 385153.766, 251563.06 ,
       240862.442, 264652.046, 339591.242, 154116.104, 179209.45 ,
       395865.984, 222158.71 ,  88837.356, 109820.532, 323821.092,
       381231.664, 397286.086, 387905.708, 304358.794, 270200.862,
       179209.45 , 377367.01 , 389712.652, 198654.19 , 284743.112,
       253124.994, 118649.706, 352740.51 , 256436.32 , 363786.346])

## 🔰 Accuracy

In [16]:
ac = accuracy_score(y_test, y_pred)

ValueError: continuous is not supported

## 🔰 r2_score

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2 = r2_score(y_test, y_pred)

In [19]:
r2

0.8413299973731136