# 🚆 Train & Test & Split

## 🧱 What is Train Data?

#### 👉 Train Data is the part of the dataset that is used to train the model (learn patterns).

#### 👉 Train data teaches the model.

### Example: By looking at student marks, the model learns how marks are calculated.

## 🧪 What is Test Data?

#### 👉 Test data is the part of the dataset that is there to check if the model has learned well.

#### 👉 Test data checks the model.

### Important: The model was not seen during test data training.

## ❓ Why is Split necessary?

#### 👉 If we give the entire data to training then:
- Model remembers answers
- Gives poor performance on real world data
- 👉 This is called Overfitting

#### 👉 Without split, model only memorizes instead of learning.

### 👉 Rule of Thumb:
- Most common = 80% Train, 20% Test

## 🔰 Import Library

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

## 🔰 Load CSV File

In [2]:
df = pd.read_csv("mobile_project.csv")

In [3]:
df

      battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0               842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1              1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2               563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3               615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4              1821     1          1.2         0  13       1  ...     2         15        1             1     0            1
...             ...   ...          ...       ...  ..     ...  ...   ...        ...      ...           ...   ...          ...
1995            794     1          0.5         1   0       1  ...     4         19        1             1     0            0
1996           1965     1          2.6         1   0       0  ...    10         16        1             1     1            2
1997           1911     0          0.9         1   1       1  ...     1          5        1             1     0            3
1998           1512     0          0.9         0   4       1  ...    10         19        1             1     1            0
1999            510     1          2.0         1   5       1  ...     4          2        1             1     1            3

[2000 rows x 21 columns]

In [4]:
df.head()

   battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0            842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1           1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2            563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3            615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4           1821     1          1.2         0  13       1  ...     2         15        1             1     0            1

[5 rows x 21 columns]

## 🔰 Missing Value Check

In [5]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

## 🔰 Separate Features (X) and Target (y)

In [6]:
y = df["battery_power"]

In [7]:
x = df.drop("battery_power", axis=1)

In [8]:
x

      blue  clock_speed  dual_sim  fc  four_g  int_memory  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0        0          2.2         0   1       0           7  ...     7         19        0             0     1            1
1        1          0.5         1   0       1          53  ...     3          7        1             1     0            2
2        1          0.5         1   2       1          41  ...     2          9        1             1     0            2
3        1          2.5         0   0       0          10  ...     8         11        1             0     0            2
4        1          1.2         0  13       1          44  ...     2         15        1             1     0            1
...    ...          ...       ...  ..     ...         ...  ...   ...        ...      ...           ...   ...          ...
1995     1          0.5         1   0       1           2  ...     4         19        1             1     0            0
1996     1          2.6         1   0       0          39  ...    10         16        1             1     1            2
1997     0          0.9         1   1       1          36  ...     1          5        1             1     0            3
1998     0          0.9         0   4       1          46  ...    10         19        1             1     1            0
1999     1          2.0         1   5       1          45  ...     4          2        1             1     1            3

[2000 rows x 20 columns]

In [9]:
y

0        842
1       1021
2        563
3        615
4       1821
        ...
1995     794
1996    1965
1997    1911
1998    1512
1999     510
Name: battery_power, Length: 2000, dtype: int64

## 🔰 Apply Train–Test Split

In [10]:
x_train, y_train, x_test, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

## 🔰 Check Shapes

In [11]:
x_train

      blue  clock_speed  dual_sim  fc  four_g  int_memory  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
968      0          0.5         1   7       0          46  ...     9          3        1             1     1            1
240      1          2.2         0   0       1          49  ...     1         16        1             1     1            2
819      0          0.9         1   2       1          57  ...    12         20        1             0     1            0
692      0          1.1         0   2       0          38  ...     8          5        0             0     1            3
420      1          0.5         1   7       0           7  ...     5         20        1             0     1            1
...    ...          ...       ...  ..     ...         ...  ...   ...        ...      ...           ...   ...          ...
1130     1          1.9         1   2       0          31  ...     5         19        0             0     1            3
1294     1          0.5         0   1       1          59  ...    10          6        1             1     1            0
860      1          0.5         0   0       1          15  ...    11         12        1             0     1            2
1459     0          0.9         1   3       0          11  ...    11         18        0             1     1            3
1126     1          0.6         1   1       1          50  ...    12         12        1             0     0            1

[1600 rows x 20 columns]

In [12]:
y_train

      blue  clock_speed  dual_sim  fc  four_g  int_memory  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
1860     0          2.5         0   3       1          25  ...     6         11        1             1     0            0
353      0          0.5         0   7       1           8  ...    17         19        1             0     0            2
1333     0          2.9         0   9       0          14  ...     1          8        1             1     0            1
905      1          2.0         0   4       0          17  ...     7         19        1             1     0            3
1289     1          0.5         1   7       0          58  ...     5          5        1             0     0            1
...    ...          ...       ...  ..     ...         ...  ...   ...        ...      ...           ...   ...          ...
965      0          0.5         1   1       0          19  ...     2         19        0             1     1            3
1284     0          2.0         0   2       1          12  ...     9         10        1             0     0            2
1739     0          1.8         0   4       1          12  ...     7         19        1             1     1            1
261      0          2.7         1   0       0          25  ...     1         12        1             1     1            1
535      0          1.9         0   0       0          31  ...     2          3        1             1     1            2

[400 rows x 20 columns]

In [13]:
x_test

968     1923
240      633
819     1236
692      781
420     1456
        ...
1130    1975
1294     589
860     1829
1459    1927
1126     635
Name: battery_power, Length: 1600, dtype: int64

In [14]:
y_test

1860    1646
353     1182
1333    1972
905      989
1289     615
        ...
965     1379
1284     991
1739    1044
261      728
535     1185
Name: battery_power, Length: 400, dtype: int64