# 🚆 Train & Test & Split

## 🔰 Import Library

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

## 🔰 Load CSV File

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [4]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

## 🔰 Missing Value Check

In [5]:
df.isnull()

     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0          False     False   False  False  False  False  False  False   False  False   True     False
1          False     False   False  False  False  False  False  False   False  False  False     False
2          False     False   False  False  False  False  False  False   False  False   True     False
3          False     False   False  False  False  False  False  False   False  False  False     False
4          False     False   False  False  False  False  False  False   False  False   True     False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...    ...    ...       ...
886        False     False   False  False  False  False  False  False   False  False   True     False
887        False     False   False  False  False  False  False  False   False  False  False     False
888        False     False   False  False  False   True  False  False   False  False   True     False
889        False     False   False  False  False  False  False  False   False  False  False     False
890        False     False   False  False  False  False  False  False   False  False   True     False

[891 rows x 12 columns]

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.drop("Cabin", axis=1, inplace=True)

In [8]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [9]:
df["Embarked"].fillna("S", inplace=True)

C:\Users\baps\AppData\Local\Temp\ipykernel_1444\2591539637.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Embarked"].fillna("S", inplace=True)

In [10]:
df["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [11]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

C:\Users\baps\AppData\Local\Temp\ipykernel_1444\1809399462.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

In [12]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## 🔰 Separate Features (X) and Target (y)

In [13]:
y = df["Survived"]

In [14]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [15]:
x = df.drop(["Survived"], axis=1)

In [16]:
x

     PassengerId  Pclass                                               Name  ...            Ticket     Fare  Embarked
0              1       3                            Braund, Mr. Owen Harris  ...         A/5 21171   7.2500         S
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  ...          PC 17599  71.2833         C
2              3       3                             Heikkinen, Miss. Laina  ...  STON/O2. 3101282   7.9250         S
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...            113803  53.1000         S
4              5       3                           Allen, Mr. William Henry  ...            373450   8.0500         S
..           ...     ...                                                ...  ...               ...      ...       ...
886          887       2                              Montvila, Rev. Juozas  ...            211536  13.0000         S
887          888       1                       Graham, Miss. Margaret Edith  ...            112053  30.0000         S
888          889       3           Johnston, Miss. Catherine Helen "Carrie"  ...        W./C. 6607  23.4500         S
889          890       1                              Behr, Mr. Karl Howell  ...            111369  30.0000         C
890          891       3                                Dooley, Mr. Patrick  ...            370376   7.7500         Q

[891 rows x 10 columns]

## 🔰 Apply Train–Test Split

In [17]:
x_train, y_train, x_test, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

## 🔰 Check Shapes

In [18]:
x_train

     PassengerId  Pclass                                Name     Sex  ...  Parch             Ticket      Fare Embarked
331          332       1                 Partner, Mr. Austen    male  ...      0             113043   28.5000        S
733          734       2          Berriman, Mr. William John    male  ...      0              28425   13.0000        S
382          383       3                  Tikkanen, Mr. Juho    male  ...      0  STON/O 2. 3101293    7.9250        S
704          705       3             Hansen, Mr. Henrik Juul    male  ...      0             350025    7.8542        S
813          814       3  Andersson, Miss. Ebba Iris Alfrida  female  ...      2             347082   31.2750        S
..           ...     ...                                 ...     ...  ...    ...                ...       ...      ...
106          107       3    Salkjelsvik, Miss. Anna Kristine  female  ...      0             343120    7.6500        S
270          271       1               Cairns, Mr. Alexander    male  ...      0             113798   31.0000        S
860          861       3             Hansen, Mr. Claus Peter    male  ...      0             350026   14.1083        S
435          436       1           Carter, Miss. Lucile Polk  female  ...      2             113760  120.0000        S
102          103       1           White, Mr. Richard Frasar    male  ...      1              35281   77.2875        S

[712 rows x 10 columns]

In [19]:
y_train

     PassengerId  Pclass                                               Name  ...             Ticket     Fare  Embarked
709          710       3  Moubarek, Master. Halim Gonios ("William George")  ...               2661  15.2458         C
439          440       2             Kvillner, Mr. Johan Henrik Johannesson  ...         C.A. 18723  10.5000         S
840          841       3                        Alhomaki, Mr. Ilmari Rudolf  ...   SOTON/O2 3101287   7.9250         S
720          721       2                  Harper, Miss. Annie Jessie "Nina"  ...             248727  33.0000         S
39            40       3                        Nicola-Yarred, Miss. Jamila  ...               2651  11.2417         C
..           ...     ...                                                ...  ...                ...      ...       ...
433          434       3                         Kallio, Mr. Nikolai Erland  ...  STON/O 2. 3101274   7.1250         S
773          774       3                                    Elias, Mr. Dibo  ...               2674   7.2250         C
25            26       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  ...             347077  31.3875         S
84            85       2                                Ilett, Miss. Bertha  ...         SO/C 14885  10.5000         S
10            11       3                    Sandstrom, Miss. Marguerite Rut  ...            PP 9549  16.7000         S

[179 rows x 10 columns]

In [20]:
x_test

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [21]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64