# 🚆 Train & Test & Split

## 🔰 Import Library

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

## 🔰 Load CSV File

In [2]:
df = pd.read_csv("StudentsPerformance.csv")

In [3]:
df

     gender race/ethnicity parental level of education  ... math score reading score  writing score
0    female        group B           bachelor's degree  ...         72            72             74
1    female        group C                some college  ...         69            90             88
2    female        group B             master's degree  ...         90            95             93
3      male        group A          associate's degree  ...         47            57             44
4      male        group C                some college  ...         76            78             75
..      ...            ...                         ...  ...        ...           ...            ...
995  female        group E             master's degree  ...         88            99             95
996    male        group C                 high school  ...         62            55             55
997  female        group C                 high school  ...         59            71             65
998  female        group D                some college  ...         68            78             77
999  female        group D                some college  ...         77            86             86

[1000 rows x 8 columns]

In [4]:
df.head()

   gender race/ethnicity parental level of education  ... math score reading score  writing score
0  female        group B           bachelor's degree  ...         72            72             74
1  female        group C                some college  ...         69            90             88
2  female        group B             master's degree  ...         90            95             93
3    male        group A          associate's degree  ...         47            57             44
4    male        group C                some college  ...         76            78             75

[5 rows x 8 columns]

## 🔰 Missing Value Check

In [5]:
df.isnull()

     gender  race/ethnicity  parental level of education  ...  math score  reading score  writing score
0     False           False                        False  ...       False          False          False
1     False           False                        False  ...       False          False          False
2     False           False                        False  ...       False          False          False
3     False           False                        False  ...       False          False          False
4     False           False                        False  ...       False          False          False
..      ...             ...                          ...  ...         ...            ...            ...
995   False           False                        False  ...       False          False          False
996   False           False                        False  ...       False          False          False
997   False           False                        False  ...       False          False          False
998   False           False                        False  ...       False          False          False
999   False           False                        False  ...       False          False          False

[1000 rows x 8 columns]

In [6]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

## 🔰 Separate Features (X) and Target (y)

In [7]:
y = df["math score"]

In [8]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [13]:
x = df.drop("math score", axis=1)

In [14]:
x

     gender race/ethnicity parental level of education  ... test preparation course reading score  writing score
0    female        group B           bachelor's degree  ...                    none            72             74
1    female        group C                some college  ...               completed            90             88
2    female        group B             master's degree  ...                    none            95             93
3      male        group A          associate's degree  ...                    none            57             44
4      male        group C                some college  ...                    none            78             75
..      ...            ...                         ...  ...                     ...           ...            ...
995  female        group E             master's degree  ...               completed            99             95
996    male        group C                 high school  ...                    none            55             55
997  female        group C                 high school  ...               completed            71             65
998  female        group D                some college  ...               completed            78             77
999  female        group D                some college  ...                    none            86             86

[1000 rows x 7 columns]

## 🔰 Apply Train–Test Split

In [16]:
x_train, y_train, x_test, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

## 🔰 Check Shapes

In [17]:
x_train

     gender race/ethnicity parental level of education  ... test preparation course reading score  writing score
29   female        group D             master's degree  ...                    none            70             75
535  female        group C           bachelor's degree  ...               completed            83             83
695  female        group D                some college  ...                    none            89             86
557    male        group C             master's degree  ...                    none            67             66
836    male        group E                 high school  ...                    none            64             57
..      ...            ...                         ...  ...                     ...           ...            ...
106  female        group D             master's degree  ...                    none           100            100
270    male        group C           bachelor's degree  ...                    none            63             61
860  female        group C          associate's degree  ...                    none            62             53
435    male        group C                some college  ...               completed            48             53
102  female        group D          associate's degree  ...                    none            91             89

[800 rows x 7 columns]

In [18]:
y_train

     gender race/ethnicity parental level of education  ... test preparation course reading score  writing score
521  female        group C          associate's degree  ...                    none            86             84
737  female        group B                some college  ...               completed            66             73
740    male        group D           bachelor's degree  ...                    none            73             72
660    male        group C                some college  ...                    none            77             73
411    male        group E                some college  ...               completed            83             78
..      ...            ...                         ...  ...                     ...           ...            ...
408  female        group D                 high school  ...               completed            57             56
332    male        group E          associate's degree  ...               completed            56             53
208  female        group B                some college  ...                    none            81             76
613  female        group C          associate's degree  ...                    none            77             74
78   female        group D            some high school  ...               completed            74             72

[200 rows x 7 columns]

In [20]:
x_test

29     62
535    66
695    79
557    61
836    73
       ..
106    87
270    69
860    53
435    50
102    85
Name: math score, Length: 800, dtype: int64

In [21]:
y_test

521    91
737    53
740    80
660    74
411    84
       ..
408    52
332    62
208    74
613    65
78     61
Name: math score, Length: 200, dtype: int64