# 🚆 Train & Test & Split

## 🔰 Import Library

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

## 🔰 Load CSV File

In [2]:
df = pd.read_csv("mobile_project.csv")

In [3]:
df

      battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0               842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1              1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2               563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3               615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4              1821     1          1.2         0  13       1  ...     2         15        1             1     0            1
...             ...   ...          ...       ...  ..     ...  ...   ...        ...      ...           ...   ...          ...
1995            794     1          0.5         1   0       1  ...     4         19        1             1     0            0
1996           1965     1          2.6         1   0       0  ...    10         16        1             1     1            2
1997           1911     0          0.9         1   1       1  ...     1          5        1             1     0            3
1998           1512     0          0.9         0   4       1  ...    10         19        1             1     1            0
1999            510     1          2.0         1   5       1  ...     4          2        1             1     1            3

[2000 rows x 21 columns]

In [4]:
df.head()

   battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0            842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1           1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2            563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3            615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4           1821     1          1.2         0  13       1  ...     2         15        1             1     0            1

[5 rows x 21 columns]

## 🔰 Missing Value Check

In [5]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

## 🔰 Separate Features (X) and Target (y)

In [6]:
df.iloc[:, [1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19]]

      blue  clock_speed  dual_sim  fc  four_g  int_memory  ...  sc_h  sc_w  talk_time  three_g  touch_screen  wifi
0        0          2.2         0   1       0           7  ...     9     7         19        0             0     1
1        1          0.5         1   0       1          53  ...    17     3          7        1             1     0
2        1          0.5         1   2       1          41  ...    11     2          9        1             1     0
3        1          2.5         0   0       0          10  ...    16     8         11        1             0     0
4        1          1.2         0  13       1          44  ...     8     2         15        1             1     0
...    ...          ...       ...  ..     ...         ...  ...   ...   ...        ...      ...           ...   ...
1995     1          0.5         1   0       1           2  ...    13     4         19        1             1     0
1996     1          2.6         1   0       0          39  ...    11    10         16        1             1     1
1997     0          0.9         1   1       1          36  ...     9     1          5        1             1     0
1998     0          0.9         0   4       1          46  ...    18    10         19        1             1     1
1999     1          2.0         1   5       1          45  ...    19     4          2        1             1     1

[2000 rows x 18 columns]

In [7]:
df.drop(df.iloc[:, [1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19]], axis=1, inplace=True)

In [8]:
df

      battery_power   ram  price_range
0               842  2549            1
1              1021  2631            2
2               563  2603            2
3               615  2769            2
4              1821  1411            1
...             ...   ...          ...
1995            794   668            0
1996           1965  2032            2
1997           1911  3057            3
1998           1512   869            0
1999            510  3919            3

[2000 rows x 3 columns]

In [9]:
y = df["price_range"]

In [10]:
x = df.drop(["price_range"], axis=1)

## 🔰 Apply Train–Test Split

In [13]:
x_train, y_train, x_test, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

## 🔰 Check Shapes

In [14]:
x_train

      battery_power   ram
836             902  3654
575            1197  2885
557            1519  2912
1235           1971   571
1360            882   751
...             ...   ...
1130           1975  3022
1294            589   362
860            1829  2080
1459           1927  2916
1126            635  2107

[1400 rows x 2 columns]

In [15]:
y_train

      battery_power   ram
1860           1646   686
353            1182  2563
1333           1972  1316
905             989  3892
1289            615  1906
...             ...   ...
148            1216  2268
1554           1957  1115
1956            555   343
925            1048  2146
942            1061   999

[600 rows x 2 columns]

In [16]:
x_test

836     3
575     2
557     2
1235    0
1360    0
       ..
1130    3
1294    0
860     2
1459    3
1126    1
Name: price_range, Length: 1400, dtype: int64

In [17]:
y_test

1860    0
353     2
1333    1
905     3
1289    1
       ..
148     2
1554    1
1956    0
925     1
942     0
Name: price_range, Length: 600, dtype: int64