# DataFrame In Pandas

In [1]:
import pandas as pd

In [2]:
data = {"Name":["Utam","Rajdeep","Adarsh"],
        "Age":[21,22,20],
        "Mark":[85,90,78]
       }

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

      Name  Age  Mark
0     Utam   21    85
1  Rajdeep   22    90
2   Adarsh   20    78

In [5]:
df.head()

      Name  Age  Mark
0     Utam   21    85
1  Rajdeep   22    90
2   Adarsh   20    78

In [6]:
df.head(2)

      Name  Age  Mark
0     Utam   21    85
1  Rajdeep   22    90

In [7]:
df.tail()

      Name  Age  Mark
0     Utam   21    85
1  Rajdeep   22    90
2   Adarsh   20    78

In [8]:
df.tail(2)

      Name  Age  Mark
1  Rajdeep   22    90
2   Adarsh   20    78

In [9]:
df.shape

(3, 3)

In [10]:
df.columns

Index(['Name', 'Age', 'Mark'], dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Mark    3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [12]:
df.describe()

        Age       Mark
count   3.0   3.000000
mean   21.0  84.333333
std     1.0   6.027714
min    20.0  78.000000
25%    20.5  81.500000
50%    21.0  85.000000
75%    21.5  87.500000
max    22.0  90.000000

In [13]:
df["Age"]

0    21
1    22
2    20
Name: Age, dtype: int64

In [14]:
df[["Name", "Mark"]]

      Name  Mark
0     Utam    85
1  Rajdeep    90
2   Adarsh    78

In [15]:
df.loc[0]

Name    Utam
Age       21
Mark      85
Name: 0, dtype: object

In [16]:
df.loc[2]

Name    Adarsh
Age         20
Mark        78
Name: 2, dtype: object

In [20]:
df.iloc[0]

Name    Utam
Age       21
Mark      85
Name: 0, dtype: object

In [21]:
df.iloc[2]

Name    Adarsh
Age         20
Mark        78
Name: 2, dtype: object

In [22]:
df[df["Mark"] > 80]

      Name  Age  Mark
0     Utam   21    85
1  Rajdeep   22    90

In [24]:
df[(df["Mark"] > 80) & (df["Age"] > 21)]

      Name  Age  Mark
1  Rajdeep   22    90

In [25]:
df["Result"] = ["Pass","Pass","Pass"]

In [26]:
df.loc[0, "Mark"] = 80

In [27]:
df.sort_values("Mark")

      Name  Age  Mark Result
2   Adarsh   20    78   Pass
0     Utam   21    80   Pass
1  Rajdeep   22    90   Pass

In [29]:
df.sort_values("Age")

      Name  Age  Mark Result
2   Adarsh   20    78   Pass
0     Utam   21    80   Pass
1  Rajdeep   22    90   Pass

In [35]:
df.sort_values("Mark", ascending=False)

      Name  Age  Mark Result
1  Rajdeep   22    90   Pass
0     Utam   21    80   Pass
2   Adarsh   20    78   Pass

In [36]:
df.sort_index()

      Name  Age  Mark Result
0     Utam   21    80   Pass
1  Rajdeep   22    90   Pass
2   Adarsh   20    78   Pass

In [37]:
df.isnull()

    Name    Age   Mark  Result
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False

In [38]:
df.isnull().sum()

Name      0
Age       0
Mark      0
Result    0
dtype: int64

In [42]:
df.dropna()

      Name  Age  Mark Result
0     Utam   21    80   Pass
1  Rajdeep   22    90   Pass
2   Adarsh   20    78   Pass

In [44]:
df.fillna(0)

      Name  Age  Mark Result
0     Utam   21    80   Pass
1  Rajdeep   22    90   Pass
2   Adarsh   20    78   Pass

In [46]:
df.groupby("Name")["Mark"].mean()

Name
Adarsh     78.0
Rajdeep    90.0
Utam       80.0
Name: Mark, dtype: float64

In [47]:
df["Mark"].apply(lambda x: x + 5)

0    85
1    95
2    83
Name: Mark, dtype: int64