# 👉CSV File With Pandas🐼

### 👉Import Pandas

In [1]:
import pandas as pd

### 👉CSV File Load

In [2]:
df = pd.read_csv("StudentsPerformance.csv")

##### ✔️ Reads a CSV file and converts it into a DataFrame.

In [11]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

### 👉CSV Data Inspect (Function)

#### ➡️ head(): first 5 rows

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

##### ✔️ Shows the first 5 rows of the data.

#### ➡️ head(): first 2 rows

In [5]:
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88

##### ✔️ Shows the first 2 rows of the data.

#### ➡️ tail(): last 5 rows

In [6]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

##### ✔️ Shows the last 5 rows of the data.

#### ➡️ tail(): last 2 rows

In [7]:
df.tail(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

##### ✔️ Shows the last 5 rows of the data.

#### ➡️ shape: (rows, columns)

In [9]:
df.shape

(1000, 8)

##### ✔️ Returns number of rows and columns.

#### ➡️ columns

In [10]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

##### ✔️ Returns all column names.

#### ➡️ index

In [12]:
df.index

RangeIndex(start=0, stop=1000, step=1)

##### ✔️ Returns row index values.

#### ➡️ dtypes

In [13]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

##### ✔️ Shows data type of each column.

### 👉Data Information

#### ➡️ info(): datatype + non-null count

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

##### ✔️ Gives summary of data (rows, columns, data type, null values).

#### ➡️ describe(): mean, min, max, std, count

In [15]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

##### ✔️ Shows statistical summary (mean, min, max, count).

### 👉Column Access (Most Important)

#### ➡️ Single Column

In [16]:
df["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

##### ✔️ Selects a single column.

#### ➡️ Multiple Column

In [17]:
df[["lunch", "gender"]]

            lunch  gender
0        standard  female
1        standard  female
2        standard  female
3    free/reduced    male
4        standard    male
..            ...     ...
995      standard  female
996  free/reduced    male
997  free/reduced  female
998      standard  female
999  free/reduced  female

[1000 rows x 2 columns]

##### ✔️ Selects a multiple column.

### 👉Row Access Methods

#### ➡️ loc (Label Based)

In [18]:
df.loc[1]

gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               69
reading score                            90
writing score                            88
Name: 1, dtype: object

##### ✔️ Selects rows using row label and column name.

#### ➡️ iloc (Index Based)

In [19]:
df.iloc[1]

gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               69
reading score                            90
writing score                            88
Name: 1, dtype: object

##### ✔️ Selects rows using index number.

#### ➡️ Row + Column

In [20]:
df.loc[2, "math score"]

np.int64(90)

### 👉Filtering Data

#### ➡️ Single Condition

In [23]:
df[df["math score"] > 90]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
34,male,group E,some college,standard,none,97,87,82
104,male,group C,some college,standard,completed,98,86,90
114,female,group E,bachelor's degree,standard,completed,99,100,100
121,male,group B,associate's degree,standard,completed,91,89,92
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
171,male,group E,some high school,standard,none,94,88,78
179,female,group D,some high school,standard,completed,97,100,100
233,male,group E,some high school,standard,none,92,87,78
263,female,group E,high school,standard,none,99,93,90
286,male,group E,associate's degree,standard,completed,97,82,88
306,male,group E,some college,standard,completed,99,87,81
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
469,male,group C,some college,standard,none,91,74,76
501,female,group B,associate's degree,standard,completed,94,87,92
503,female,group E,associate's degree,standard,completed,95,89,92
521,female,group C,associate's degree,standard,none,91,86,84
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
562,male,group C,bachelor's degree,standard,completed,96,90,92
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
571,male,group A,bachelor's degree,standard,none,91,96,92
594,female,group C,bachelor's degree,standard,completed,92,100,99
612,male,group C,bachelor's degree,standard,completed,94,90,91
618,male,group D,master's degree,standard,none,95,81,84
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
685,female,group E,master's degree,standard,completed,94,99,100
689,male,group E,some college,free/reduced,none,93,90,83
710,male,group C,some college,standard,completed,93,84,90
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
719,male,group E,associate's degree,free/reduced,completed,91,73,80
736,male,group C,associate's degree,standard,none,92,79,84
779,male,group E,associate's degree,standard,completed,94,85,82
784,male,group C,bachelor's degree,standard,completed,91,81,79
815,male,group B,some high school,standard,completed,94,86,87
846,male,group C,master's degree,standard,completed,91,85,85
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
919,male,group B,some college,standard,completed,91,96,91
934,male,group C,associate's degree,standard,completed,98,87,90
950,male,group E,high school,standard,none,94,73,71
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
979,female,group C,associate's degree,standard,none,91,95,94

##### ✔️ Filters data based on condition.

#### ➡️ Multiple Condition

In [24]:
df[(df["math score"] > 95) & (df["reading score"] > 90)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
114,female,group E,bachelor's degree,standard,completed,99,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
179,female,group D,some high school,standard,completed,97,100,100
263,female,group E,high school,standard,none,99,93,90
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
539,male,group A,associate's degree,standard,completed,97,92,86
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100

#### ➡️ isin()

In [25]:
df[df["race/ethnicity"].isin(["group A","group B"])]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
983,female,group A,some college,standard,completed,78,87,91
985,male,group A,high school,standard,none,57,51,54
988,female,group A,some high school,free/reduced,none,44,45,45
991,female,group B,some high school,standard,completed,65,82,78
994,male,group A,high school,standard,none,63,63,62

### 👉Missing Values Handling (NaN)

#### ➡️ Check Missing

In [26]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

##### ✔️ Checks missing values (NaN).

#### ➡️ Count Missimg

In [27]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

##### ✔️ Counts missing values column-wise.

#### ➡️ Drop Missimg Rows

In [28]:
df.dropna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

##### ✔️ Removes rows with missing values.

#### ➡️ Fill Missing

In [29]:
df["writing score"].fillna(df["writing score"].mean())

0      74
1      88
2      93
3      44
4      75
       ..
995    95
996    55
997    65
998    77
999    86
Name: writing score, Length: 1000, dtype: int64

In [30]:
df["writing score"].fillna(df["writing score"].mean(), inplace=True)

C:\Users\baps\AppData\Local\Temp\ipykernel_8032\3294227657.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["writing score"].fillna(df["writing score"].mean(), inplace=True)

##### ✔️ Fills missing values with given value.

### 👉Data Modification

#### ➡️ New Column and apply()

In [31]:
df["Result"] = df["math score"].apply(lambda x: "Pass" if x >= 40 else "Fail")

In [32]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Result
0,female,group B,bachelor's degree,standard,none,72,72,74,Pass
1,female,group C,some college,standard,completed,69,90,88,Pass
2,female,group B,master's degree,standard,none,90,95,93,Pass
3,male,group A,associate's degree,free/reduced,none,47,57,44,Pass
4,male,group C,some college,standard,none,76,78,75,Pass
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,Pass
996,male,group C,high school,free/reduced,none,62,55,55,Pass
997,female,group C,high school,free/reduced,completed,59,71,65,Pass
998,female,group D,some college,standard,completed,68,78,77,Pass
999,female,group D,some college,free/reduced,none,77,86,86,Pass

In [33]:
df[df["math score"] < 40]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Result
9,female,group B,high school,free/reduced,none,38,60,50,Fail
17,female,group B,some high school,free/reduced,none,18,32,28,Fail
55,female,group C,high school,free/reduced,none,33,41,43,Fail
59,female,group C,some high school,free/reduced,none,0,17,10,Fail
61,male,group A,some high school,free/reduced,none,39,39,34,Fail
69,female,group C,associate's degree,standard,none,39,64,57,Fail
76,male,group E,some high school,standard,none,30,26,22,Fail
91,male,group C,high school,free/reduced,none,27,34,36,Fail
145,female,group C,some college,free/reduced,none,22,39,33,Fail
211,male,group C,some college,free/reduced,none,35,28,27,Fail
217,female,group C,high school,free/reduced,none,34,42,39,Fail
284,female,group B,some high school,standard,none,37,46,46,Fail
327,male,group A,some college,free/reduced,none,28,23,19,Fail
338,female,group B,some high school,free/reduced,none,24,38,27,Fail
339,female,group D,some high school,free/reduced,completed,35,55,60,Fail
363,female,group D,some high school,free/reduced,none,27,34,32,Fail
383,female,group E,some high school,free/reduced,none,38,49,45,Fail
384,female,group A,some high school,free/reduced,none,38,43,43,Fail
455,male,group C,bachelor's degree,free/reduced,none,37,56,47,Fail
466,female,group D,associate's degree,free/reduced,none,26,31,38,Fail
527,female,group C,high school,free/reduced,none,36,53,43,Fail
528,female,group D,bachelor's degree,free/reduced,none,29,41,47,Fail
555,female,group C,some college,free/reduced,none,32,39,33,Fail
596,male,group B,high school,free/reduced,none,30,24,15,Fail
601,female,group C,high school,standard,none,29,29,30,Fail
616,female,group E,bachelor's degree,standard,none,37,45,38,Fail
620,female,group C,high school,free/reduced,none,35,61,54,Fail
683,female,group C,some high school,free/reduced,completed,29,40,44,Fail
741,female,group A,associate's degree,free/reduced,none,37,57,56,Fail
777,female,group C,some college,free/reduced,none,35,44,43,Fail
785,female,group B,some high school,standard,completed,32,51,44,Fail
787,female,group B,some college,standard,none,19,38,32,Fail
840,female,group D,high school,free/reduced,none,39,52,46,Fail
842,female,group B,high school,free/reduced,completed,23,44,36,Fail
862,male,group D,bachelor's degree,free/reduced,completed,39,42,38,Fail
895,female,group E,some high school,free/reduced,none,32,34,38,Fail
896,male,group B,high school,free/reduced,none,36,29,27,Fail
902,female,group A,high school,free/reduced,completed,34,48,41,Fail
921,female,group C,high school,free/reduced,none,35,53,46,Fail
980,female,group B,high school,free/reduced,none,8,24,23,Fail

##### ✔️ Adds a new column and Applies a function to each value.

#### ➡️ Update Value

In [34]:
df.loc[61, "math score"] = 40

### 👉Sorting Data

#### ➡️ Ascending

In [35]:
df.sort_values("writing score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Result
59,female,group C,some high school,free/reduced,none,0,17,10,Fail
596,male,group B,high school,free/reduced,none,30,24,15,Fail
327,male,group A,some college,free/reduced,none,28,23,19,Fail
76,male,group E,some high school,standard,none,30,26,22,Fail
980,female,group B,high school,free/reduced,none,8,24,23,Fail
...,...,...,...,...,...,...,...,...,...
916,male,group E,bachelor's degree,standard,completed,100,100,100,Pass
114,female,group E,bachelor's degree,standard,completed,99,100,100,Pass
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100,Pass
403,female,group D,high school,standard,completed,88,99,100,Pass
165,female,group C,bachelor's degree,standard,completed,96,100,100,Pass

#### ➡️ Descending

In [37]:
df.sort_values("writing score", ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Result
962,female,group E,associate's degree,standard,none,100,100,100,Pass
957,female,group D,master's degree,standard,none,92,100,100,Pass
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100,Pass
165,female,group C,bachelor's degree,standard,completed,96,100,100,Pass
114,female,group E,bachelor's degree,standard,completed,99,100,100,Pass
...,...,...,...,...,...,...,...,...,...
980,female,group B,high school,free/reduced,none,8,24,23,Fail
76,male,group E,some high school,standard,none,30,26,22,Fail
327,male,group A,some college,free/reduced,none,28,23,19,Fail
596,male,group B,high school,free/reduced,none,30,24,15,Fail
59,female,group C,some high school,free/reduced,none,0,17,10,Fail

##### ✔️ Sorts data by column.

### 👉Aggregation & Statistics

#### ➡️ mean, max, min, sum, count

In [38]:
df["math score"].mean()

np.float64(66.09)

In [39]:
maxi = df["math score"].max()

In [40]:
maxi

np.int64(100)

In [41]:
df["math score"].min()

np.int64(0)

In [42]:
df["math score"].sum()

np.int64(66090)

In [43]:
df["math score"].count()

np.int64(1000)

##### ✔️ mean(): Calculates average.
##### ✔️ sun(): Calculates total.
##### ✔️ min(): Minimum value.
##### ✔️ max(): Maximum value.
##### ✔️ count(): Counts non-missing values.

### 👉GroupBy (Very Important)

#### ➡️ Single Condition

In [44]:
df.groupby("race/ethnicity")["math score"].mean()

race/ethnicity
group A    61.640449
group B    63.452632
group C    64.463950
group D    67.362595
group E    73.821429
Name: math score, dtype: float64

##### ✔️ Groups data and performs calculation.

#### ➡️ Multiple Condition

In [46]:
df.groupby("race/ethnicity").agg({
    "math score": ["mean", "max"],
    "writing score": "mean"
})

               math score      writing score
                     mean  max          mean
race/ethnicity
group A         61.640449  100     62.674157
group B         63.452632   97     65.600000
group C         64.463950   98     67.827586
group D         67.362595  100     70.145038
group E         73.821429  100     71.407143

##### ✔️ Groups data and performs calculation.
##### ✔️ agg(): Applies multiple calculations at once.

### 👉Apply, Map and Replace

#### ➡️ apply()

In [49]:
df["reading score"].apply(lambda x : x - 5)

0      67
1      85
2      90
3      52
4      73
       ..
995    94
996    50
997    66
998    73
999    81
Name: reading score, Length: 1000, dtype: int64

##### ✔️ Applies a function to each value.

#### ➡️ map()

In [50]:
df["race/ethnicity"].map({"group A":1, "group B":2})

0      2.0
1      NaN
2      2.0
3      1.0
4      NaN
      ...
995    NaN
996    NaN
997    NaN
998    NaN
999    NaN
Name: race/ethnicity, Length: 1000, dtype: float64

##### ✔️ Maps old values to new values.

#### ➡️ replace()

In [51]:
df["lunch"].replace("standard", "free/reduced", inplace=True)

C:\Users\baps\AppData\Local\Temp\ipykernel_8032\3698330205.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["lunch"].replace("standard", "free/reduced", inplace=True)

##### ✔️ Replaces specific values.

### 👉Merge/join CSV Files

In [54]:
# pd.merge(df, df, on="mark score", how="inner")

##### ✔️ Joins two DataFrames.
##### ✔️ inner
##### ✔️ left
##### ✔️ right
##### ✔️ outer

### 👉Duplicate Handling

In [55]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

##### ✔️ Checks duplicate rows.

In [57]:
df.drop_duplicates()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Result
0,female,group B,bachelor's degree,free/reduced,none,72,72,74,Pass
1,female,group C,some college,free/reduced,completed,69,90,88,Pass
2,female,group B,master's degree,free/reduced,none,90,95,93,Pass
3,male,group A,associate's degree,free/reduced,none,47,57,44,Pass
4,male,group C,some college,free/reduced,none,76,78,75,Pass
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,free/reduced,completed,88,99,95,Pass
996,male,group C,high school,free/reduced,none,62,55,55,Pass
997,female,group C,high school,free/reduced,completed,59,71,65,Pass
998,female,group D,some college,free/reduced,completed,68,78,77,Pass
999,female,group D,some college,free/reduced,none,77,86,86,Pass

##### ✔️ Removes duplicate rows.

### 👉CSV Save Functions

#### ➡️ Save CSV

In [58]:
df.to_csv("StudentData.csv", index=False)

##### ✔️ Saves DataFrame to CSV file.

#### ➡️ Save Selected Columns

In [ ]:
df[["race/ethnicity", "math score"]].to_csv("StudentData.csv", index=False)